# Generated by Django 6.0.6 on 2026-07-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='expected_devtool',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='idea',
            name='interest',
            field=models.IntegerField(default=0),
        ),
    ]
