# Generated by Django 5.2.4 on 2026-07-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='nutrition/')),
                ('calories', models.FloatField(blank=True, null=True, verbose_name='칼로리(kcal)')),
                ('carbohydrate', models.FloatField(blank=True, null=True, verbose_name='탄수화물(g)')),
                ('protein', models.FloatField(blank=True, null=True, verbose_name='단백질(g)')),
                ('fat', models.FloatField(blank=True, null=True, verbose_name='지방(g)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
        ),
    ]
